### model
model_name_or_path: /home/yfye/pre-trained/Llama-3.1-8B

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: deepspeed/ds_z3_config.json

### dataset
dataset: aya_train_mini_parallel
template: llama3   # chosing the template
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16


### output
output_dir: saves/Llama-3.1-8B/full_sft/aya_train_mini_parallel
logging_steps: 10
plot_loss: true
overwrite_output_dir: true
save_strategy: epoch

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.01
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
