#!/bin/bash
#SBATCH -J check                               # 作业名为 test
#SBATCH -o slurm-%j.out                       # 屏幕上的输出文件重定向到 slurm-%j.out , %j 会替换成jobid
#SBATCH -e slurm-%j.err                       # 屏幕上的错误输出文件重定向到 slurm-%j.err , %j 会替换成jobid
#SBATCH -p compute                            # 作业提交的分区为 compute
#SBATCH -N 1                                  # 作业申请 1 个节点
#SBATCH -t 10:00:00                           # 任务运行的最长时间为 1 小时
#SBATCH -w gpu07                           # 指定运行作业的节点是 gpu06，若不填写系统自动分配节点
#SBATCH --gres=gpu:nvidia_rtx_a6000:1                         # 单个节点使用 1 块 GPU 卡
#SBATCH --mem=80GB  # 80 GB


source ~/.bashrc

# 设置运行环境
export PATH="/users12/yfye/anaconda3/bin:$PATH"
source activate CC-Tuning


# python get_vectors.py --model_name /home/yfye/ACL2025_2/Evaluation/saves_mini_parallel/Llama-3.1-8B/full/sft_mlp_source_2/epoch-3 --save_folder llama

python get_matrix.py --read_folder llama --save_folder llama